### ISSUE TITLE
Shared library built but not installed

### ISSUE THREAD

**Issue by lgbaldoni** [fontobene/fontobene-qt5#9]
Using openSUSE Tumbleweed.

Is it perhaps done on purpose in order to test if the library can be built at all?

**Comment by ubruhin** [comment]
It's a header-only library, so it doesn't make much sense to build as shared library from it :)

**Comment by lgbaldoni** [comment]
@ubruhin 
I couldn't agree more, but then why do I see this?
```
> ls -l fontobene-qt5-0.1.0/fontobene-qt5/lib*
lrwxrwxrwx 1 abuild abuild    25 Oct  4 19:32 fontobene-qt5-0.1.0/fontobene-qt5/libfontobene-qt5.so -> libfontobene-qt5.so.1.0.0
lrwxrwxrwx 1 abuild abuild    25 Oct  4 19:32 fontobene-qt5-0.1.0/fontobene-qt5/libfontobene-qt5.so.1 -> libfontobene-qt5.so.1.0.0
lrwxrwxrwx 1 abuild abuild    25 Oct  4 19:32 fontobene-qt5-0.1.0/fontobene-qt5/libfontobene-qt5.so.1.0 -> libfontobene-qt5.so.1.0.0
-rwxr-xr-x 1 abuild abuild 16544 Oct  4 19:32 fontobene-qt5-0.1.0/fontobene-qt5/libfontobene-qt5.so.1.0.0
```

**Comment by ubruhin** [comment]
As far as I remember, this is actually not intended, but Qt always creates a shared library even if no source files are present. See: https://github.com/fontobene/fontobene-qt5/blob/b57b075c9472ee57eba76ee0ee96357367853dce/fontobene-qt5/fontobene-qt5.pro#L1-L4

**Comment by lgbaldoni** [comment]
I see. How about using the aux template and making the test building conditional?

**Comment by dbrgn** [comment]
Hi @lgbaldoni. We just published version 0.2.0 of the library and now offer CMake support as well.

I'd recommend updating the package and replacing qmake with cmake. The pkg-config file needs to be updated as well, the old version had a bug with regards to the include path.

Does that resolve your issue?

**Comment by lgbaldoni** [comment]
Thanks, everything looks fine now.

**Comment by dbrgn** [comment]
Great to hear!
